### PR TITLE
Bootstrap friendly

### PR DESCRIPTION
**Pull request by mnot**
This pull is intended to make the CSS names more friendly to a bootstrap-based stylesheet.

### CODE REVIEW

**Comment by reschke** [comment]
I'd like to treat CSS-related changes separately and first.

Combining rfc2629.xslt's output with other material is indeed problematic due to potential CSS class name collisions. This is not restricted to your use case, so I'd like to have a solution that works everywhere. Another related problem is that the v3 formatter specs probably will require hard-wired CSS class names which I then wouldn't be able to change anymore.

It seems that this particular problem (CSS collisions when used embedded into other pages, or when puling in additional material) could be addresses by an XSLT parameter that defines a string prefix uses for all CSS. Would that address the CSS-related issue behind this pull request?

**Comment by mnot** [comment]
I don't think so -- bootstrap's CSS names are hardwired as well, and not prefixed.

I only think it'll actually present a problem when there's a genuine clash in names, and we can't use CSS selectors to distinguish between them. 

That said, I have started defining variables (see later commits) to allow extra classes to be applied to specific elements where they're needed. Perhaps if that were taken a bit further, it'd be workable.

**Comment by mnot** [comment]
Oh, and BTW - as of now, this pull has everything I need, _except_ for changing the ToC code to allow collapsing. I'm going to need to take a closer look to figure out the best (and least intrusive) approach for that, but it's separable from this.

FWIW - the XSLT that imports this to do the bootstrap version is now only ~180 lines (including CSS).

**Comment by mnot** [comment]
WRT h1 - surely the page title should be h1, and individual sections be h2 and onwards?

I mean, I can work around this, but it seems like pretty universal practice..,

**Comment by reschke** [comment]
"I don't think so -- bootstrap's CSS names are hardwired as well, and not prefixed."

Bad bad bootstrap :-)

What I meant is that I could make the CSS names in rfc2629.xslt optionally prefixed. Would that work for you?

**Comment by mnot** [comment]
Not sure I follow; can you give an example?

**Pull request closed without merging**
